### ISSUE TITLE
Please rename the component

### ISSUE THREAD

**Issue by t3lmoazevedo** [ulic75/power-distribution-card#15]
Hi, this component gets in conflict with another power-distribution-card using the same name:
https://github.com/JonahKr/power-distribution-card

Its there a way to have both? Maybe renaming it?
Thanks

**Comment by t3lmoazevedo** [comment]
For those that have already the component https://github.com/JonahKr/power-distribution-card this new one will not load and shows an error on HA. 
Maybe rename to power-distribution-card-enhance :)

**Comment by RogerSelwyn** [comment]
This card generates this error in HACS:

`2022-05-09 15:36:03 ERROR (MainThread) [custom_components.hacs] <HacsTask prosess_queue> failed: Repository structure for v1.0.0 is not compliant`

**Comment by RogerSelwyn** [comment]
> @RogerSelwyn Are you suggesting you're receiving this error because you already have the card from JonahKr installed? This looks like a separate issue maybe. Also the latest version of this card is 1.2.0, so I'm not sure why it would say v1.0.0.

I have no cards installed, but got this error in my dev environment when I started some other testing this afternoon, so debugged HACS which says it is  the `realtime-energy-distribution-card` which is `<Plugin ulic75/power-distribution-card>`. 

It looks like it is a different error though, it goes away if I make my external url accessible (I tend to lock down external access to be Dev when I don't need it). Not sure why it has picked your plugin to complain about.

**Comment by PimDoos** [comment]
HACS is still installing it to `/config/www/community/power-distribution-card` for me, perhaps this file should also be updated?
https://github.com/ulic75/power-flow-card/blob/main/package.json
![image](https://user-images.githubusercontent.com/17709721/167489153-2504a55b-ce6f-429b-a2a9-8aa99a99e771.png)

**Comment by ulic75** [comment]
It takes time for the HACS to update the information on there end of things.  Unfortunately we're at their mercy on that front.
