### ISSUE TITLE
Suggestion: option to separate grid sensors for consumption & production

### ISSUE THREAD

**Issue by timvdsm** [ulic75/power-distribution-card#8]
Hi, I see you use 1 sensor for grid. 
Grid: entity providing a state with a positive value when consuming and a negative value when producting.
However I do have a separate sensor for grid consumption and a separate sensor for grid production. 
Any possibility to add this separation? 

Btw: absolute great card! Many thanks for your work!

**Comment by ulic75** [comment]
Hmm, yes in hindsight that may be better, I was simply trying to avoid having extra entities in the config.  Let me think on the best way to handle that without breaking changes.

Thank you for the kind words, frankly I'm surprised no one did it until now :)
